kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
- role: control-plane
  image: kindest/node:v1.15.7
- role: worker
  image: kindest/node:v1.15.7
  extraPortMappings:
  - containerPort: 5900
    hostPort: 5900
    listenAddress: "127.0.0.1"
