apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubedoom
  name: kubedoom-0
  namespace: kubedoom
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kubedoom-0
  ports:
  - protocol: TCP
    port: 5900
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubedoom
  name: kubedoom-1
  namespace: kubedoom
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kubedoom-1
  ports:
  - protocol: TCP
    port: 5900
    nodePort: 31001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubedoom
  name: kubedoom-2
  namespace: kubedoom
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: kubedoom-2
  ports:
  - protocol: TCP
    port: 5900
    nodePort: 31002