# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: kubedoom
#   name: kubedoom
#   namespace: kubedoom
# spec:
#   type: NodePort
#   ports:
#   - name: vnc
#     port: 5900
#     targetPort: vnc
#   selector:
#     app: kubedoom
