---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kubedoom
  name: kubedoom
  namespace: kubedoom
spec:
  replicas: 3
  serviceName: kubedoom-service
  selector:
    matchLabels:
      app: kubedoom
  template:
    metadata:
      labels:
        app: kubedoom
    spec:
      serviceAccountName: kubedoom
      containers:
        - image: ghcr.io/storax/kubedoom:latest
          env:
            - name: NAMESPACE
              value: kubedoom
          name: kubedoom
          ports:
            - containerPort: 5900
              name: vnc
